[2019-08-17 21:47:54 +0530] [25191] [DEBUG] Current configuration:
  config: gunicorn.conf.py
  bind: ['127.0.0.1:9000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /Users/vijesh/djangochart/mychart
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 501
  group: 20
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /Users/vijesh/djangochart/mychart/logs/gunicorn-access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /Users/vijesh/djangochart/mychart/logs/gunicorn-error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: unix:///var/run/syslog
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  statsd_prefix: 
  proc_name: None
  default_proc_name: mychart.wsgi.py
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x1080bd8c8>
  on_reload: <function OnReload.on_reload at 0x1080bd9d8>
  when_ready: <function WhenReady.when_ready at 0x1080bdae8>
  pre_fork: <function Prefork.pre_fork at 0x1080bdbf8>
  post_fork: <function Postfork.post_fork at 0x1080bdd08>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x1080bde18>
  worker_int: <function WorkerInt.worker_int at 0x1080bdf28>
  worker_abort: <function WorkerAbort.worker_abort at 0x1082950d0>
  pre_exec: <function PreExec.pre_exec at 0x1082951e0>
  pre_request: <function PreRequest.pre_request at 0x1082952f0>
  post_request: <function PostRequest.post_request at 0x108295378>
  child_exit: <function ChildExit.child_exit at 0x108295488>
  worker_exit: <function WorkerExit.worker_exit at 0x108295598>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x1082956a8>
  on_exit: <function OnExit.on_exit at 0x1082957b8>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: TLSv1
  raw_paste_global_conf: []
[2019-08-17 21:47:54 +0530] [25191] [INFO] Starting gunicorn 19.9.0
[2019-08-17 21:47:54 +0530] [25191] [DEBUG] Arbiter booted
[2019-08-17 21:47:54 +0530] [25191] [INFO] Listening at: http://127.0.0.1:9000 (25191)
[2019-08-17 21:47:54 +0530] [25191] [INFO] Using worker: sync
[2019-08-17 21:47:54 +0530] [25194] [INFO] Booting worker with pid: 25194
[2019-08-17 21:47:54 +0530] [25191] [DEBUG] 1 workers
[2019-08-17 16:17:55 +0000] [25194] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/vijesh/djangochart/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/vijesh/djangochart/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/vijesh/djangochart/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/vijesh/djangochart/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/vijesh/djangochart/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/vijesh/djangochart/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/vijesh/djangochart/venv/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'mychart.wsgi.py'; 'mychart.wsgi' is not a package
[2019-08-17 16:17:55 +0000] [25194] [INFO] Worker exiting (pid: 25194)
[2019-08-17 21:47:55 +0530] [25191] [INFO] Shutting down: Master
[2019-08-17 21:47:55 +0530] [25191] [INFO] Reason: Worker failed to boot.
[2019-08-17 21:54:51 +0530] [25214] [DEBUG] Current configuration:
  config: gunicorn.conf.py
  bind: ['127.0.0.1:9000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /Users/vijesh/djangochart/mychart
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 501
  group: 20
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /Users/vijesh/djangochart/mychart/logs/gunicorn-access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /Users/vijesh/djangochart/mychart/logs/gunicorn-error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: unix:///var/run/syslog
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  statsd_prefix: 
  proc_name: None
  default_proc_name: mychart.wsgi
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x10a6f68c8>
  on_reload: <function OnReload.on_reload at 0x10a6f69d8>
  when_ready: <function WhenReady.when_ready at 0x10a6f6ae8>
  pre_fork: <function Prefork.pre_fork at 0x10a6f6bf8>
  post_fork: <function Postfork.post_fork at 0x10a6f6d08>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x10a6f6e18>
  worker_int: <function WorkerInt.worker_int at 0x10a6f6f28>
  worker_abort: <function WorkerAbort.worker_abort at 0x10a8ce0d0>
  pre_exec: <function PreExec.pre_exec at 0x10a8ce1e0>
  pre_request: <function PreRequest.pre_request at 0x10a8ce2f0>
  post_request: <function PostRequest.post_request at 0x10a8ce378>
  child_exit: <function ChildExit.child_exit at 0x10a8ce488>
  worker_exit: <function WorkerExit.worker_exit at 0x10a8ce598>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x10a8ce6a8>
  on_exit: <function OnExit.on_exit at 0x10a8ce7b8>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: TLSv1
  raw_paste_global_conf: []
[2019-08-17 21:54:51 +0530] [25214] [INFO] Starting gunicorn 19.9.0
[2019-08-17 21:54:51 +0530] [25214] [DEBUG] Arbiter booted
[2019-08-17 21:54:51 +0530] [25214] [INFO] Listening at: http://127.0.0.1:9000 (25214)
[2019-08-17 21:54:51 +0530] [25214] [INFO] Using worker: sync
[2019-08-17 21:54:51 +0530] [25217] [INFO] Booting worker with pid: 25217
[2019-08-17 21:54:51 +0530] [25214] [DEBUG] 1 workers
[2019-08-17 16:25:04 +0000] [25217] [DEBUG] GET /api/data
[2019-08-17 16:25:04 +0000] [25217] [DEBUG] GET /favicon.ico
[2019-08-17 16:25:23 +0000] [25217] [DEBUG] GET /mypage
[2019-08-17 16:25:23 +0000] [25217] [DEBUG] GET /api/data
[2019-08-17 16:25:33 +0000] [25217] [DEBUG] GET /mypage1
[2019-08-17 16:25:33 +0000] [25217] [DEBUG] GET /api/data
[2019-08-17 16:25:33 +0000] [25217] [DEBUG] GET /api/data1
[2019-08-17 16:26:18 +0000] [25217] [DEBUG] GET /mypage1
[2019-08-17 16:26:18 +0000] [25217] [DEBUG] GET /api/data
[2019-08-17 16:26:18 +0000] [25217] [DEBUG] GET /api/data1
[2019-08-17 16:26:23 +0000] [25217] [DEBUG] GET /mypage1
[2019-08-17 16:26:23 +0000] [25217] [DEBUG] GET /api/data
[2019-08-17 16:26:23 +0000] [25217] [DEBUG] GET /api/data1
[2019-08-17 16:26:57 +0000] [25217] [DEBUG] GET /mypage1
[2019-08-17 16:26:58 +0000] [25217] [DEBUG] GET /api/data
[2019-08-17 16:26:58 +0000] [25217] [DEBUG] GET /api/data1
[2019-08-18 03:52:51 +0530] [25214] [CRITICAL] WORKER TIMEOUT (pid:25217)
[2019-08-17 22:22:51 +0000] [25217] [INFO] Worker exiting (pid: 25217)
[2019-08-18 03:52:51 +0530] [25351] [INFO] Booting worker with pid: 25351
[2019-08-18 11:47:09 +0530] [25214] [CRITICAL] WORKER TIMEOUT (pid:25351)
[2019-08-18 06:17:09 +0000] [25351] [INFO] Worker exiting (pid: 25351)
[2019-08-18 11:47:09 +0530] [25471] [INFO] Booting worker with pid: 25471
[2019-08-18 12:16:11 +0530] [25214] [INFO] Handling signal: int
[2019-08-18 06:46:11 +0000] [25471] [INFO] Worker exiting (pid: 25471)
[2019-08-18 12:16:11 +0530] [25214] [INFO] Shutting down: Master
